name: dooflii_clinic_app
description: "A Flutter clinic management app."

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.10.3
  provider: ^6.1.5+1
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  uuid: ^4.5.2
  flutter_hooks: ^0.21.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true